language: ruby
os: linux
dist: xenial
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
- 2.7
env:
  global:
    secure: cOq5uGx7o0OtWTr401dUGSOgD6ahseSFhQ1KLLzjDQ3Dwrl2d3CaaS7rMQL+e3s4PQIh7Ud4yRMIzKvpU4iJx0o1KV0upAuZDvOZvycuTq5xtbBS1YIMwCXFxfZ91PBrBlaWLiSGQwbtXdX+GFHPc4W3Mxb8pX4HaWYJfhwjnEKZQ5gwrGqy3Txx4eenDgTaYFj037NO9/DRgWW2IEyVIeArlw7inNATzh2IhjKHqhUcM+88cXFwlooWvxzxmCtvJWqOnhN1PWCzlrCQaCT8PorZTMF4bG/VKHWm2+gi9WY0CYIlUSCeAzYRzUbQ1dMKwcZc0stSwuvF45EfWAx8dkmAKHkYMO9bgoxhyPVXYTGYnJj65wlwi+wivwGVrz2hng0+WlZ61d34AoKkJ5AVcuKaL+RovVndEn7bPxLQ3pv8U9MlcUUPcHLfEyqTECIZdBkQXHalggbko/tx3WehuYyEljw+vqIAGUvryzO9pPGUtKD2fwmArpgy/Iqjt4zNKmz7gX/ZvdCs5hoec4ihVyf8CONWU/dFX3B9+Rw/wnJtEZbzAWnKuItKrNeMked1NgWDItSWeDUpE8BFL5Cnw2kGJBx04x283F7b54KHd2Pb9famxVtNecu0NJfvVK2OOeLcLpfdh3I6xQsUwXGG4kJzVmXqhagT+maKR8KtiEM=
jobs:
  include:
  - stage: Build & Deploy Gem
    script: ".vnops/rubygems/deploy.sh"
    rvm: 2.7
    if: tag =~ /^v*/
